version: '3.8'

services:
  # Frontend React application
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
    networks:
      - app-network

  # Backend Node.js application
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=production
      # Uncomment and update these for PostgreSQL in production
      # - DB_USER=postgres
      # - DB_HOST=db
      # - DB_NAME=conversation_app
      # - DB_PASSWORD=password
      # - DB_PORT=5432
    networks:
      - app-network
    # Uncomment to add database service
    # depends_on:
    #   - db

  # Uncomment to add PostgreSQL database service for production
  # db:
  #   image: postgres:14-alpine
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=password
  #     - POSTGRES_DB=conversation_app
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge

# Uncomment for PostgreSQL persistence
# volumes:
#   postgres-data: 