[build]
  command = "npm run build"
  publish = ".next"
  environment = { NODE_VERSION = "18", NPM_VERSION = "10", NEXT_PUBLIC_SUPABASE_URL = "your-supabase-url" }

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Needed for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 