[build]
  command = "CI= npm run build"
  publish = "build"
  environment = { NODE_VERSION = "18", NPM_VERSION = "10", NEXT_PUBLIC_SUPABASE_URL = "your-supabase-url" }

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Handle API routes for Auth0
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 