[build]
  command = "CI= npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "10"
  NEXT_TELEMETRY_DISABLED = "1"
  SECRETS_SCAN_OMIT_PATHS = ".env.production,.netlify/**/*.env.production,Auth0-Configuration.md"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Handle API routes for Auth0
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 